version: "0.1"
services:
  db:
    container_name: db
    image: postgres:14-alpine
    stdin_open: true # docker run -i
    tty: true # docker run -t
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  telegram:
    container_name: telegram
    build: ./telegram
    depends_on:
      - images
      - youtube

  images:
    container_name: images
    build: ./images

  youtube:
    container_name: youtube
    build: ./youtube

volumes:
  db:
    driver: local
