version: "0.1"
services:
  db:
    container_name: db
    image: postgres:14-alpine
    stdin_open: true # docker run -i
    tty: true # docker run -t
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  jekabot:
    container_name: jekabot
    build: ./app
    depends_on:
      - db

volumes:
  db:
    driver: local
