dev:
  token: 5302691216:AAHi_3cSkJKO2KYUDY3TwCfPt1Q-wLrj94I
  botSign: sadfoiewjfoiwlejf_bot
  jekaRealid: Jekadesigner
  pavelychRealId: dabdabdabdayada
  # souceChatID: -621831810
  souceChatID: -377297062

prod:
  token: 5181534861:AAExYEVuJj1sc6PRooZMwOmqB7XT-hp9NJ8
  botSign: ggyhhhh_bot
  jekaRealid: Jekadesigner
  pavelychRealId: dabdabdabdayada
  # souceChatID: -621831810
  souceChatID: -377297062

